### PR TITLE
Don't crash on bogus assign_filtration

### LINKED ISSUE #756: Crash on assign_filtration
For a given SimplexTree() if I assign a filtration value to an edge that is not in the one skeleton, the program crashes :
```
import gudhi as gd
st = gd.SimplexTree()
st.assign_filtration([0, 1], 3.14)
```
Instead should we:
- raise an exception?
- insert the edge `st.insert([0, 1])` and assign anyway?

### PR DESCRIPTION
**Pull request by mglisse**
Fix #756.

### CODE REVIEW

File: src/python/include/Simplex_tree_interface.h [hunk 1]
```diff
@@ -53,7 +53,10 @@ class Simplex_tree_interface : public Simplex_tree<SimplexTreeOptions> {
   }
 
   void assign_simplex_filtration(const Simplex& simplex, Filtration_value filtration) {
-    Base::assign_filtration(Base::find(simplex), filtration);
+    Simplex_handle sh = Base::find(simplex);
+    if (sh == Base::null_simplex())
+      throw std::invalid_argument("Cannot assign a filtration to a simplex that is not in the complex");
```
Comment (VincentRouvreau) [inline src/python/include/Simplex_tree_interface.h:58]: Should we explain that the python method will throw an exception in simplex is not found ? `ValueError` in python

Comment (VincentRouvreau) [reply src/python/include/Simplex_tree_interface.h:58]: "Obvious" exceptions seem to be not documented under python cf.  [numpy.genfromtxt](https://numpy.org/devdocs/reference/generated/numpy.genfromtxt.html#numpy-genfromtxt), `np.genfromtxt("unexisting_file.txt")` throws a `FileNotFoundError`
