### PR TITLE
Fix fast cofaces for insert_batch_vertices

### LINKED ISSUE #970: [Simplex_tree] insert_batch_vertices shall call update_simplex_tree_after_node_insertion
On #877 insert_batch_vertices was not considered and this method shall call update_simplex_tree_after_node_insertion for cofaces/stars to work when`link_nodes_by_label` is activated

### PR DESCRIPTION
**Pull request by VincentRouvreau**
Fix #970 
To be discussed if storing information in a `std::vector<Vertex_handle>` is a good idea or not.

### CODE REVIEW

File: src/Simplex_tree/include/gudhi/Simplex_tree.h [hunk 1]
```diff
@@ -1317,10 +1317,26 @@ class Simplex_tree {
    * already present, its filtration value is not modified, unlike with other insertion functions. */
   template <class VertexRange>
   void insert_batch_vertices(VertexRange const& vertices, Filtration_value filt = 0) {
+    // When Options::link_nodes_by_label, update_simplex_tree_after_node_insertion must be called only if
+    // not already inserted - copy vertex handles from flat_map
+    std::vector<Vertex_handle> old_members(root_.members().size());
+    if constexpr (Options::link_nodes_by_label) {
+      for (auto sh = root_.members().begin(); sh != root_.members().end(); sh++)
+        old_members.emplace_back(sh->first);
```
Comment (mglisse) [inline src/Simplex_tree/include/gudhi/Simplex_tree.h:1325]: You create old_members that contains n copies of 0 then append the rest to it? Did you mean to use reserve instead?

File: src/Simplex_tree/include/gudhi/Simplex_tree.h [hunk 2]
```diff
@@ -1317,10 +1317,26 @@ class Simplex_tree {
...
+    }
+
     auto verts = vertices | boost::adaptors::transformed([&](auto v){
-        return Dit_value_t(v, Node(&root_, filt)); });
+      return Dit_value_t(v, Node(&root_, filt)); });
     root_.members_.insert(boost::begin(verts), boost::end(verts));
     if (dimension_ < 0 && !root_.members_.empty()) dimension_ = 0;
+    for (auto sh = root_.members().begin(); sh != root_.members().end(); sh++) {
+      if constexpr (Options::link_nodes_by_label) {
+        if (std::find(old_members.begin(), old_members.end(), sh->first) == std::end(old_members))
```
Comment (mglisse) [inline src/Simplex_tree/include/gudhi/Simplex_tree.h:1334]: No, using std::find yields a quadratic cost, whereas both vectors are sorted so it would be possible to walk on both at the same time in linear time.

File: src/Simplex_tree/include/gudhi/Simplex_tree.h [hunk 3]
```diff
@@ -1317,10 +1317,26 @@ class Simplex_tree {
...
+          update_simplex_tree_after_node_insertion(sh);
+      } else {
+        update_simplex_tree_after_node_insertion(sh);
```
Comment (mglisse) [inline src/Simplex_tree/include/gudhi/Simplex_tree.h:1337]: I don't understand why this appears in both branches, but with a test in one branch?

**Review by mglisse — COMMENTED** [review]
Try a simple loop with `if(!x.is_linked()) update(x);`, it will be less likely to go wrong.

File: src/Simplex_tree/include/gudhi/Simplex_tree.h [hunk 4]
```diff
@@ -1321,6 +1321,12 @@ class Simplex_tree {
         return Dit_value_t(v, Node(&root_, filt)); });
     root_.members_.insert(boost::begin(verts), boost::end(verts));
     if (dimension_ < 0 && !root_.members_.empty()) dimension_ = 0;
+    if constexpr (Options::link_nodes_by_label) {
+      for (auto sh = root_.members().begin(); sh != root_.members().end(); sh++) {
+        if (nodes_label_to_list_.find(sh->first) == nodes_label_to_list_.end())
```
Comment (mglisse) [inline src/Simplex_tree/include/gudhi/Simplex_tree.h:1326]: Or something like
```suggestion
        if (!sh->second.list_max_vertex_hook_.is_linked())
```
?
