### PR TITLE
Handle duplicated points in choose_n_farthest_points

### LINKED ISSUE #404: Sparse RipsComplex RuntimeError
Hi,

I got an "Unknown exception" error with sparse RipsComplex when I try to normalize the point positions as the following:
```
import tadasets
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import pairwise_distances
import time
import gudhi as gd

X = tadasets.infty_sign(n=100, noise=0.0)
X = (X + 1) / 2 # error with this line
tic = time.time()
D = pairwise_distances(X, metric='euclidean')
rips = gd.RipsComplex(distance_matrix=D, max_edge_length=42, sparse=0.1)
simplex_tree = rips.create_simplex_tree(max_dimension=2)
diag = simplex_tree.persistence(homology_coeff_field=2, min_persistence=0)
toc = time.time()
print ('Elapsed Time: {:.4f}'.format(toc-tic))
```

Error messages:
`File "rips_complex.pyx", line 102, in gudhi.rips_complex.RipsComplex.create_simplex_tree
RuntimeError: Unknown exception`

Is there any restriction for using the sparse rips complex ? Thanks for your help.

### PR DESCRIPTION
**Pull request by mglisse**
Fix #404.

### CODE REVIEW

File: src/Subsampling/test/test_choose_n_farthest_points.cpp [hunk 1]
```diff
@@ -93,7 +93,15 @@ BOOST_AUTO_TEST_CASE_TEMPLATE(test_choose_farthest_point_limits, Kernel, list_of
...
-  // Choose all farthest points in a one point cloud
+  // Choose all farthest points among 2 points
+  Gudhi::subsampling::choose_n_farthest_points(k, points, -1, -1, std::back_inserter(landmarks), std::back_inserter(distances));
+  BOOST_CHECK(landmarks.size() == 2 && distances.size() == 2);
+  BOOST_CHECK(distances[0] == std::numeric_limits<FT>::infinity());
+  BOOST_CHECK(distances[1] == 1);
+  landmarks.clear(); distances.clear();
+
+  // Ignore duplicated points
+  points.push_back(Point_d(point.begin(), point.end()));
```
Comment (VincentRouvreau) [inline src/Subsampling/test/test_choose_n_farthest_points.cpp:104]:
```suggestion
points.emplace_back(point.begin(), point.end());
```

**Review by VincentRouvreau — APPROVED** [review]

File: src/Subsampling/test/test_choose_n_farthest_points.cpp (hunk 1 above)
Comment (mglisse) [reply src/Subsampling/test/test_choose_n_farthest_points.cpp:104]: Ah, yes, I copy-pasted from a few lines above without looking too closely...
